### ISSUE TITLE
Could not load type 'Umbraco.Cms.Core.Deploy.IGridCellValueConnector2'

### ISSUE THREAD

**Issue by callumbwhyte** [umbraco/Umbraco.Deploy.Issues#147]
Trying to upgrade one of our Cloud sites to v11 and getting the following error locally preventing the application from booting. Looks like something is missing...

```
TypeLoadException: Could not load type 'Umbraco.Cms.Core.Deploy.IGridCellValueConnector2' from assembly 'Umbraco.Infrastructure, Version=11.0.0.0, Culture=neutral, PublicKeyToken=null'.
```

The package references we have in our csproj are as follows:

```
<PackageReference Include="Microsoft.ICU.ICU4C.Runtime" Version="68.2.0.9" />
<PackageReference Include="Umbraco.Cloud.Identity.Cms" Version="11.0.18" />
<PackageReference Include="Umbraco.Cloud.StorageProviders.AzureBlob" Version="11.0.0" />
<PackageReference Include="Umbraco.Cms" Version="11.0.0" />
<PackageReference Include="Umbraco.Deploy.Cloud" Version="11.0.0" />
<PackageReference Include="Umbraco.Deploy.Contrib" Version="11.0.0" />
<PackageReference Include="Umbraco.Deploy.Forms" Version="11.0.0" />
<PackageReference Include="Umbraco.Forms" Version="11.0.0" />
```

**Comment by ronaldbarendse** [comment]
Hi Callum! We did change related interfaces in 11.0.0-rc2 (PR https://github.com/umbraco/Umbraco-CMS/pull/13287), but since that introduced breaking changes, reverted those and added new versions, including `IGridCellValueConnector2` in 11.0.0-rc6 (PR https://github.com/umbraco/Umbraco-CMS/pull/13489). Your project seems to be using an outdated assembly that doesn't contain this interface, hence the error...

You can verify that the `Umbraco.Infrastructure` version 11.0.0.0 assembly does contain the `Umbraco.Cms.Core.Deploy.IGridCellValueConnector2` type on [FuGet](https://www.fuget.org/packages/Umbraco.Cms.Infrastructure/11.0.0/net7.0/lib/Umbraco.Infrastructure.dll/Umbraco.Cms.Core.Deploy/IGridCellValueConnector2).

Maybe your local NuGet cache contains the wrong version (use `dotnet nuget locals all --clear` to clear this) or a package is preventing the transitive dependency on `Umbraco.Cms.Infrastructure` to update to the final 11.0.0 version?

**Comment by callumbwhyte** [comment]
Thanks @ronaldbarendse, you were absolutely right here!
