### ISSUE TITLE
Data extraction fails as unable to map Forms prevalues

### ISSUE THREAD

**Issue by snerpton** [umbraco/Umbraco.Deploy.Issues#16]
Data extraction fails in a fresh local dev environment. Log suggests this is because Deploy is unable to map Forms PreValueSourceArtifact.

Issue has been raised with Umbraco Cloud support 30 July 2019. Eric confirmed (31 July 2019):

> The developers have isolated the problem and have made a task in order to solve it.
> It will end up as a new release for deploy

Eric later said the task was scheduled for next week, but Sophie later said on 15 August 2019 that the task was in the backlog but was yet to be prioritised. She suggested creating this ticket to raise visibility of the issue.

Reproduction
------------

- Create an Umbraco Form in Umbraco Cloud
- Create form prevalue with values: 0) "We use SSL", 1) "We don't use SSL", 2) "I don't know what SSL is", and 3) "I don't know"
- Clone project to local dev machine
- Restore content (it'll fail)
- Deploy marker file `deploy-failed` is now in `/data`. You can try deleting this and `echo > deploy` but it always fails. I've uploaded [/data/deploy.log](https://github.com/umbraco/Umbraco.Cloud.Issues/files/3551029/deploy.log) to this issue.

Umbraco Cloud Environment:
- Umbraco 8.1.3
- Forms 8.1.2
- Deploy 3.1.1

Expected result
----------------

Restoring content to fresh local development environment should succeed.

Actual result
-------------

Restore of content fails, seemingly because the Deploy fails (see uploaded log file).

**Comment by AndyButland** [comment]
As far as I can tell, with the latest Deploy I'm not seeing this problem.  Have tested a deployment of a form with a prevalue source, and both are transferred correctly.  So hopefully it's been fixed in meantime from when this issue was last looked at.

Can also see a commit for _"Added missing mapping for FieldPreValueSource"_ from late May 2020, so looks like that was what resolved it.

As such will close, but please let me know anyone if you are stil seeing this issue on a more recent version of Deploy.

**Comment by msinnott22** [comment]
We are facing this issue with Deploy 4.1 using Umbraco Heartcore
