### ISSUE TITLE
Permissions for Empty Deploy Section on Heartcore

### ISSUE THREAD

**Issue by cornehoskam** [umbraco/Umbraco.Deploy.Issues#166]
### Issue description

Hi Umbraco HQ,

I feel like this is an issue, and I couldn't find anyone else having reported it yet, so here we go!
While configuring permissions on some groups in Heartcore I stumbled upon the option to add the "Deploy" section under a User Groups "Assign Access" -> "Sections" option. The content of this section is completely empty however, so I suspect this isn't intentional?

See attached screenshots.
![image](https://github.com/umbraco/Umbraco.Heartcore.Issues/assets/6321978/7deb72ac-75ff-49c6-9375-5ce32e82277d)

![image](https://github.com/umbraco/Umbraco.Heartcore.Issues/assets/6321978/59364f9f-c53c-43a5-9f20-b2ab58f0efed)

If it isn't an issue/bug, I'm curious to what the purpose of this section is! 😄

Kind regards,
Corné Hoskam

**Comment by AndyButland** [comment]
It's unfortunate, but currently necessary.  IIRC it's due to having the ability to have a tree controller in Deploy that allows you to pick content from an upstream environment to restore.  That uses a customized tree, similar to one you'd have in the CMS for content, media etc.  As a tree needs to live in a section, there needs to be one in order to create it - and it can't be an existing section or you'd get this "external content tree" appearing where it shouldn't.  Hence this "hidden" one is created and used.

Obviously it's not fully hidden as you, and now and then others, have found it. But it can just be ignored.

**Comment by cornehoskam** [comment]
Thank you for the in-depth explanation Andy! Always interesting to know the science behind what's going on behind-the-scenes!
