### ISSUE TITLE
IDE warns about missing ApiKey in Deploy settings

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Deploy.Issues#168]
I noticed the intellisense in Visual Studio warns about a missing ApiKey property under "Deploy > Settings" in appsettings.json as it is required.

![image](https://github.com/umbraco/Umbraco.Deploy.Issues/assets/2919859/8c32503f-f56d-4ed2-87b5-8d23c71a327e)

But on Umbraco Cloud this isn't required.
I guess the schema model is generated from a class, where the "ApiKey" property is marked as required?

**Comment by AndyButland** [comment]
It's still required on Cloud, but it's defined in the `umbraco-cloud.json` file and for Cloud only, this setting is read from there.

@ronaldbarendse - I'm guessing we can't do much about this warning showing when it isn't necessary to act on fir Cloud?

**Comment by ronaldbarendse** [comment]
> I'm guessing we can't do much about this warning showing when it isn't necessary to act on for Cloud?

We've removed the data annotations in v12 (and moved it to a custom validation callback), so the generated JSON schema doesn't list the API key as a required property anymore. You can ignore this warning on Cloud sites, since the API key is indeed read from the `umbraco-cloud.json` settings file.

This is really a more general configuration/validation issue, because you can have multiple configuration sources that can't be successfully validated separately, but when combined _will_ be valid.
