### ISSUE TITLE
Media Start Node missing when project is exported with UDA files /umbraco/backoffice/umbracoapi/mediatype/GetAllowedChildren

### ISSUE THREAD

**Issue by juanlondonoforero** [umbraco/Umbraco.Deploy.Issues#177]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

11.4.2

### Bug summary

I have a document type with an Image field that points to a starting node in the media folder. When the project is exported with UDA files the document type misses the starting node because the folder doesn't exist in the new environment, but even if the new media folder is created in the new environment the document type can't find it because it's using the media folder ID (not the name)

### Steps to reproduce

Create document type with and Image field
Set the starting node to a specific new folder in the media structure
Move the project to a new environment
The media folder structure doesn't exist so the doctType will generate an error.
Creating the media folder wont resolve the issue because the DocType uses the folder ID not the name

### Expected result / actual result
I expected to be able to select an image form the Content page, but instead I get /umbraco/backoffice/umbracoapi/mediatype/GetAllowedChildren
_No response_

**Comment by andr317c** [comment]
Hey

This sounds like a deploy issue, which is why I have transferred this issue to deploy 😄

**Comment by juanlondonoforero** [comment]
Thanks Anders
To sum up: we uncommented the wwwroot as described in the screenshot 1; and we added the front end tasks  in the pipeline that copies the CSS/JS folders to wwwroot (screenshot 2 step 3)
The artifacts file is created correctly with all the css/js flders in the wwwroot but they are not displayed in the U-Cloud wwwroot folder

Thanks

Juan
***@***.***



***@***.***

**Comment by AndyButland** [comment]
Unfortunately I don't think there's a perfect solution to this scenario.  This issue is that, as you've found, the definition of the data type contains a reference to the start folder using it's GUID based identifier.  When an item in Umbraco is created via the backoffice, it's assigned a GUID, and as such even if you create an item with the same name in two environments, it'll have a different GUID set.

Most Umbraco data is clearly separable into that managed by developers (document types, data types) and that by editors (content, media), but sometimes, as in this case, there's an overlap where a "schema" item depends on something managed as "content".

I feel that all you can do here is to ensure that your media folders have consistent GUIDs between environments.  If setting up from scratch, you could create the data type and media folder in a development environment.  The `.uda` file for the data type will have a reference to the folder by GUID.  And if you use the content transfer facilities to deploy your media folders into the upstream environment, rather than recreating them there directly, they'll have the same GUID and be identified.

Another approach would be to write some code in a composer that runs on start up, that creates the folders you need, with the appropriate GUIDs, if they don't already exist.

If you already have environments setup, you could remove the start folder from the data type, deploy the schema, transfer the media folders and then re-add the start folder to the data type again.

Finally, you can amend the GUIDs via a database query such that they match between environments.  Please make sure to test and backup before running, particularly in production, but something like this can be used to update the GUIDs in the database:

```
DECLARE @id as uniqueidentifier

USE devdb

SET @id = (
	SELECT uniqueid
	FROM umbracoNode
	WHERE nodeObjectType = 'B796F64C-1F99-4FFB-B886-4BF4BC011A9C' and text = 'My Folder Name')

USE proddb

UPDATE umbracoNode
SET uniqueid = @id
WHERE nodeObjectType = 'B796F64C-1F99-4FFB-B886-4BF4BC011A9C' and text = 'My Folder Name'
```
