### ISSUE TITLE
Umbraco Forms - schema mismatch (Umbraco Cloud editing)

### ISSUE THREAD

**Issue by AdamczykMaciej** [umbraco/Umbraco.Deploy.Issues#192]
A brief description of the issue goes here.

I have a custom data type (let's call it Form Picker - which utilizes Umbraco Form Picker).
Let's say I have a cloud environment and a cloud environment.

Imagine, content editor creates an Umbraco Form and adds it to the Form Picker as an allowed form.
It it very logical and normal that such a situation will happen. 
Such activity diverges the Umbraco Cloud schema from Umbraco Local schema.

After this action, one can't restore content from Cloud because the schema has changed.
The same would apply to a situation in which I change something locally - but that's not a big problem. I can push those changed to Cloud or just remove them.

--------
How can we solve that?
Adding allowed forms on Umbraco Cloud diverges the schema and gives an error locally when restoring content (schema mismatch)

**Comment by AndyButland** [comment]
The issue here is that the form picker, being a data type, is considered as "schema".  This, along with document types, media types etc. are generally considered something that a developer will be in charge of.  They'll be created locally and pushed up to the Cloud site, along with the templates and any other code that uses it.

Here you are giving the editor the ability not only to work with "content" (Umbraco content, media and forms), but also, in this one case, "schema" too.  I can see that it makes sense that you allow editors to do this, but it's a little out of the normal flow used with Cloud (and, under the hood, Umbraco Deploy).

There's a few things you could consider here.

1. There is an option with Umbraco Deploy to configure it in "backoffice edition" (see [here](https://docs.umbraco.com/umbraco-deploy/deploy-settings#edition)).  This is an option where all schema can be transferred via the backoffice.  That would solve the issue for you I think, but it does break this normal flow that I've described above (where there's a clear separation of what developers control, and what editors too).  So you might feel this is too much change for just this one issue.

2. You could make your form creation flow like the following:
- Editor create the form but doesn't touch the data types.
- Developer pulls the form locally and updates the form picker data type.
- Developer pushes the change to the data type.

3. Umbraco Cloud uses git repositories for it's deployment between local and the Cloud environment(s).  When you change the data type on the Cloud site, the change will be committed to the git repository as a change to the data types `.uda` file.  If you pull that locally, you should be able to merge it with your local environment, and after that should be able to restore the form itself, and any other content, from Cloud - as the "schema" will now match.

**Comment by AdamczykMaciej** [comment]
@AndyButland , thank you for your answer.
Number 1, BackOfficeOnly - having this option on, will .uda files still be created ? From what I understand it'll give us a possibility to transfer settings through BackOffice as you transfer Content from one environment to another one.
I wonder, whether uda files will be used for synchronisation or we will have to everything through the Transfer Queue.

Number 2/3, they are a bit tricky because in Umbraco Cloud you have 3 environments: Dev, Stage, Live so it might be quite cumbersome to do it for every cloud environment - merging to our private source code repository.

Content Editors/Testers should be able to add forms to Allowed forms without developer's interaction.
For 1 Cloud environment that could be good enough, but when having 2, 3 environments it will become tedious.

**Comment by AdamczykMaciej** [comment]
Anyways, it could be challenging and not trivial to synchronize local with cloud even with 1 cloud environment, depending on how often Content Editors/Testers make changes to Allowed Forms and how many Form Pickers we have.

**Comment by AndyButland** [comment]
I agree, I don't think any of these are ideal solutions.  The first would work, but as I noted it does diverge from the normal separation of concerns between what's managed by developers (schema, deployed via serialization to disk) and editors (content, deployed via the back-office).

One other approach - again not ideal, but perhaps feasible - is that your developers create the "form stubs".  So forms with names only, that you can associated with your form picker data types and deploy all into your environment where the editors work.  The editors then edit the forms - amending all the fields etc.  So in other words developers create and delete forms, editors only edit them.  Of course it means whenever an editor needs to create a form, they have to ask a developer to do it, but perhaps that's workable if you have some advance notice of what you are going to need.

---

As discussed it's tricky to solve this nicely with Deploy.  Probably the approach needs to be to improve the form picker so you could select forms more dynamically, probably via picking a folder that gives you access to all the forms inside it.

**Comment by AdamczykMaciej** [comment]
Yes, I think enabling folder selection in Form Picker  or/and querying could be really nice improvements and would help a lot. Of course there could be a case that Content Editors need to pick specific forms and add them to allowed forms - this solution won't solve this problem. I think adding the option to select folders would be really nice. It won't solve all scenarios but it will add a bit of dynamics.

**Comment by AdamczykMaciej** [comment]
Do you know when it could be implemented @AndyButland? I think it would help a lot of people having multilingual/multiwebsite setups.

**Comment by AndyButland** [comment]
It's in our backlog, but as I'm sure you'll appreciate efforts are mostly focussed on Umbraco 14 right now, so I suspect it'll be something we look at in the second half of the year.

**Comment by AndyButland** [comment]
The option to define folders for which forms can be selected will be part of the the upcoming Forms release 14.2 and 15.0.
