### ISSUE TITLE
All progress messages showing when doing a content transer/restore

### ISSUE THREAD

**Issue by ghost** [umbraco/Umbraco.Deploy.Issues#205]
Today you "only" get one message at a time when content transfering, or restoring, such as "Review manifest on target" or "Create manifest on target"

Please do this:

![image](https://github.com/umbraco/Umbraco.Deploy.Issues/assets/82879686/06784e72-2006-4dd8-9605-4ad22aa523b3)

Correnction and clarifying of descriptive text in the image: Let newest message be at the top, i.e. insert at the top.

I only included two messages here in my mock but the point should get across; let's make some use of all that blank space with each new log message, as they could be inserted at the top, so you can get a grip on how long each step take, when you started etc - such data is useful to have collected :)

Thank you!

**Comment by ronaldbarendse** [comment]
Thanks for this suggestion! We do want to keep the UI clean though and since this is a progress bar, the most important thing is to know what it's currently doing.

If you do want to get insights in the full log history, you can use the Log Viewer, as each of these messages are written as INFO to the Umbraco log... This is in the Settings section, so I do acknowledge not all users might have access to it.

We are rewriting the UI for the new backoffice in v14, so I'll tag this as idea, in case we want to include it while reworking the dialogs 👍🏻
