### ISSUE TITLE
Umbraco.Deploy.Core.Exceptions.ProcessArtifactException: "Cannot save content with an empty name."

### ISSUE THREAD

**Issue by daandrnorlysdk1** [umbraco/Umbraco.Deploy.Issues#222]
When trying to restore content, it currently fails to restore content that has "vary by culture" (+ empty fields?)

Issue on **Umbraco Cloud** version: **14.0.0**

How to replicate:

1. Make a document type, enable "varying by culture"
2. Fill out content for 1 culture, but not another
3. Try to restore this content on another environment and it will fail

Jacob from Support has tried this and got the same error:
https://downloads.intercomcdn.com/i/o/1070888236/59570ddd6833bc52b0a15ac5/image.png?expires=1718271000&signature=81fbba8c9c3db3c2d87ed07b8e2d0e4be67fbd5e2ef6279e0ba0cfa55f6975a5

**Comment by ronaldbarendse** [comment]
Thanks for reporting this @daandrnorlysdk1 🙌🏻 

I've been able to replicate this error and although it originates from the CMS (see [`DocumentRepository`](https://github.com/umbraco/Umbraco-CMS/blob/contrib/src/Umbraco.Infrastructure/Persistence/Repositories/Implement/DocumentRepository.cs#L1683-L1692)), it's a regression in Deploy 14 introduced when rewriting the internals to support async services (as a lot of services in CMS 14 now have async methods, new services are even exclusively async).

The fix is included in Deploy 14.0.2 and just released to NuGet, so you can already manually upgrade (or wait until it's automatically upgraded next week).
