### ISSUE TITLE
Umbraco V14 Dashboard: Trial Expiry & Missing Translation

### ISSUE THREAD

**Issue by warrenbuckley** [umbraco/Umbraco.Deploy.Issues#229]
### Issue description

The Cloud/Deploy dashboard has a trial expiry but has a very specific decimal.
If we are to display more precise than days, than I suggest it gets converted to days and hours and once under the 24 hour mark it could be turned into hours and minutes.

See screenshot for context:
![image](https://github.com/umbraco/Umbraco.Cloud.Issues/assets/1389894/02bb0e6d-f64a-4c79-bdec-c8d1de0bce27)

Additionally as shown in the screenshot you can see there is a missing translation for `deploy_UpgradeNow`

---
_This item has been added to our backlog AB#42654_

**Comment by ronaldbarendse** [comment]
Thanks for reporting this @warrenbuckley 💪🏻 We've fixed the issue in the latest Deploy 14.1.0 release, so it now contains a rounded amount of days. We've omitted displaying hours/minutes, because that would've required more logic/external dependencies and doesn't really provide much more value. The button also has a translation now and when expired changes into a more urgent yellow/warning color:

![Trial expires in](https://github.com/user-attachments/assets/da9850dc-694d-462c-9384-ed5a02918fd3)

![Expired](https://github.com/user-attachments/assets/d888f6a7-edf3-451b-aced-2bad28d584b9)
