### ISSUE TITLE
Importing Legacy DocTypeGridEditor Configurations Fails When 'alias' Differs from 'allowedDocTypes' in Umbraco Deploy

### ISSUE THREAD

**Issue by Cris-Speak** [umbraco/Umbraco.Deploy.Issues#236]
# Importing Legacy DocTypeGridEditor Configurations Fails When 'alias' Differs from 'allowedDocTypes' in Umbraco Deploy

Importing an exported ZIP file containing legacy Block Grid (DocTypeGridEditor) configurations into an Umbraco 13 project fails when the `alias` in the `gridEditor` differs from the `allowedDocTypes` specified in its configuration.

Reproduction
------------

### Bug summary

When attempting to import an exported ZIP from an Umbraco 8.6.1 environment into an Umbraco 13.4.1 project, the import fails if the legacy Block Grid (DocTypeGridEditor) configurations have a `gridEditor` `alias` that differs from the `allowedDocTypes` specified in its configuration. The migration process throws an exception stating that it cannot find the content type with the alias specified in `allowedDocTypes`, even though it exists.

### Specifics

- **Source Environment (Exported From):**
  - **Umbraco Version:** 8.6.1
  - **Packages Installed:**
    - UmbracoDeploy.OnPrem 4.10
    - UmbracoDeploy.Contrib 4.4.0
    - Our.Umbraco.DocTypeGridEditor 1.2.9

- **Target Environment (Imported To):**
  - **Umbraco Version:** 13.4.1
  - **Packages Installed:**
    - Umbraco.Deploy.Contrib 13.3.0
    - Umbraco.Deploy.Cloud 13.2.2

- **Error Message:**
```
System.InvalidOperationException: Migrating legacy grid failed, because content type with alias 'brancheSlider' could not be found (in the Block Grid configuration). Umbraco.Deploy.Core.Exceptions.ProcessArtifactException: Process pass #5 failed for artifact umb://document/1481d40556fd409ca8f01903d7f8b41f. Umbraco.Deploy.Core.Exceptions.ImportArtifactsUnhandledException: An unhandled exception has occurred during the import.
```

### Steps to reproduce

1. **In the Umbraco 8.6.1 project:**

 - Install and configure DocTypeGridEditor.
 - Create a grid editor configuration where the `alias` differs from the `allowedDocTypes`. For example:

   ```json
   {
     "name": "Diensten slider",
     "alias": "slider",
     "view": "/App_Plugins/DocTypeGridEditor/Views/doctypegrideditor.html",
     "render": "/App_Plugins/DocTypeGridEditor/Render/DocTypeGridEditor.cshtml",
     "icon": "icon icon-billboard",
     "config": {
       "allowedDocTypes": [ "brancheSlider" ],
       "nameTemplate": "Diensten slider",
       "enablePreview": false,
       "viewPath": "/Views/Partials/Grid/Editors/Custom/",
       "previewViewPath": "/Views/Partials/Grid/Editors/Custom/Preview",
       "previewCssFilePath": "",
       "previewJsFilePath": ""
     }
   }
   ```

 - Ensure that a content type with the alias `brancheSlider` exists.

2. **Export the project:**

 - Use Umbraco Deploy to generate an export ZIP file of the project.

3. **In the Umbraco 13.4.1 project:**

 - Set up a fresh Umbraco 13.4.1 environment with the necessary Deploy packages installed.
 - Attempt to import the exported ZIP file using Umbraco Deploy.

4. **Observe the error:**

 - The import process fails with the aforementioned exception.

### Expected result

The import process should complete successfully, migrating the legacy DocTypeGridEditor configurations to the new Block Grid format. The legacy grid should be properly migrated, even when the `alias` in the `gridEditor` differs from the `allowedDocTypes` in its configuration.

### Actual result

The import process fails with an exception, preventing the migration from completing. The error indicates that the content type with alias `brancheSlider` could not be found in the Block Grid configuration, even though it exists in the project.

**Error Details:**
```
System.InvalidOperationException: Migrating legacy grid failed, because content type with alias 'brancheSlider' could not be found (in the Block Grid configuration). Umbraco.Deploy.Core.Exceptions.ProcessArtifactException: Process pass #5 failed for artifact umb://document/1481d40556fd409ca8f01903d7f8b41f. Umbraco.Deploy.Core.Exceptions.ImportArtifactsUnhandledException: An unhandled exception has occurred during the import.
 ```
 
This issue does not occur when the `alias` and the `allowedDocTypes` in the `gridEditor` configuration are the same. For example, the following configuration imports successfully:

```json
{
  "name": "Steps",
  "alias": "uSPSteps",
  "view": "/App_Plugins/DocTypeGridEditor/Views/doctypegrideditor.html",
  "render": "/App_Plugins/DocTypeGridEditor/Render/DocTypeGridEditor.cshtml",
  "icon": "icon-ordered-list",
  "config": {
    "allowedDocTypes": [ "uSPSteps" ],
    "nameTemplate": "Steps",
    "enablePreview": false,
    "viewPath": "/Views/Partials/Grid/Editors/Custom/",
    "previewViewPath": "/Views/Partials/Grid/Editors/Custom/Preview",
    "previewCssFilePath": "",
    "previewJsFilePath": ""
  }
}
```

[uda files.zip](https://github.com/user-attachments/files/17257358/uda.files.zip)

**Comment by ronaldbarendse** [comment]
Hi Cris, thanks for reporting this issue in such detail!

Going from the examples and steps you provided, I can see you're using custom grid editor configurations in v8, but not copying the `grid.editors.config.js` file(s) over to the v13 project or customizing the default `ReplaceDocTypeGridEditorDataTypeArtifactMigrator` to handle them.

This artifact migrator adds the default DTGE grid editor in the [`GetGridEditors()` method](https://github.com/umbraco/Umbraco.Deploy.Contrib/blob/e42f98febb7d6c83c4e7222444b30339fe13e5a3/src/Umbraco.Deploy.Contrib/Migrators/ReplaceDocTypeGridEditorDataTypeArtifactMigrator.cs#L85-L104), besides the ones loaded from the `grid.editors.config.js` files. This means you don't have to do any extra steps when migrating if you only use the default configuration DTGE ships with.

If the project you're importing to doesn't have the custom grid editor configurations, it falls back to looking up an element type by the grid editor alias. This explains why a 1:1 alias match still works, but it doesn't if the missing grid editor configuration used a different alias in the `allowedDocTypes` setting.

Looking [at the documentation](https://docs.umbraco.com/umbraco-deploy/13.deploy.latest-lts/deployment-workflow/import-export/import-with-migrations#grid-to-block-grid), I do see this is mentioned:
> The available editors are retrieved from the `grid.editors.config.js` files (can be overridden in `GetGridEditors()`).

But I acknowledge that this definitely needs to be stated more clearly and repeated in the 'Migrating From Doc Type Grid Editor` paragraph.

Can you confirm whether the migration does work correctly after copying the `grid.editors.config.js` file over or adding them in the package manifests (as [per documentation](https://docs.umbraco.com/umbraco-cms/13.latest-lts/fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/grid-layout/grid-editors))?

**Comment by Cris-Speak** [comment]
Hi Ronald,

Thanks for your input! After reviewing the documentation you shared, I came up with a slightly different approach. Instead of modifying the `grid.editors.config.js` file, I moved the `App_Plugins\DocTypeGridEditor\package.manifest` file from the old Umbraco 8 project to the new Umbraco 13 project. This resolved the issue, and the import ran smoothly, migrating all the content, doctypes, and media as expected.

Thanks for your help!

**Comment by ronaldbarendse** [comment]
Hi Cris, that's great to hear! I've created a PR to update the documentation and make this more clear now as well👌🏻

**Comment by keck-marcel** [comment]
@ronaldbarendse I've recently come across something very similar here and merely including the `App_Plugins\DocTypeGridEditor\package.manifest` did not work for me. I am using custom DTGE entries and am trying to migrate them from v10 to v13

I have done the following while trying to do this:

1. Exported the site on Umbraco 10 using Umbraco Deploy
2. Upgraded the project to the latest v13 (13.5.2) at the time of writing this
3. Run the solution on a fresh v13 installation with Umbraco Deploy and the contrib package installed
4. Import the export zip from earlier

On import I get to a DTGE and get the following error message `Migrating legacy grid failed, because content type with alias 'cardCollection' could not be found (in the Block Grid configuration)`

Before I start extending the `GetGridEditors` method should the `App_Plugins\DocTypeGridEditor\package.manifest` be automatically picked up by the `ReplaceDocTypeGridEditorDataTypeArtifactMigrator`

Should we merely create a `grid.editors.config.js` in a `config/` folder and put all of our custom editors in that file as well?

Thanks

**Comment by ronaldbarendse** [comment]
@keck-marcel Copying the custom DTGE entries from the `package.manifest` or `grid.editors.config.js` files to the v13 project should be enough, as those will be parsed and returned by the CMS (using `IGridConfig.EditorsConfig`, see [implementation](https://github.com/umbraco/Umbraco-CMS/blob/2d4230c001777ea51851ffcec64b976840132207/src/Umbraco.Core/Configuration/Grid/GridEditorsConfig.cs#L59-L141)).

Have you also updated the Deploy Contrib package to 10.3.0 on the original site before exporting? I believe the issue has to do with the order of processing/importing the artifacts, so the content type with alias 'cardCollection' can't be found, because it hasn't been imported yet when the grid migrator runs, see PR https://github.com/umbraco/Umbraco.Deploy.Contrib/pull/65.

If you can't update the original site and do another export, you can also first import the element types separately (by creating a ZIP file with only the `document-type__*.uda` and `data-type__*.uda` files) or you can create a custom `ReplaceDocTypeGridEditorDataTypeArtifactMigrator` that overrides [`MigrateDocTypeGridEditor(...)`](https://github.com/umbraco/Umbraco.Deploy.Contrib/blob/e7b9f0d0521940948ba35337b2302f3d9068ec8f/src/Umbraco.Deploy.Contrib/Migrators/ReplaceDocTypeGridEditorDataTypeArtifactMigrator.cs#L119-L132) to manually map the alias to the correct GUID(s).

**Comment by keck-marcel** [comment]
@ronaldbarendse thanks for the reply, I will export the original site with 10.3.0 Contrib package and report back. I previously had exported with 10.3.0 but will do so again for documentation/vetting purposes.

Will report back - thank you!

**Comment by hfloyd** [comment]
I'm coming across a similar error (migrating a v.8.18.15 site to 13.5.2)

The v13 site has "Umbraco.Deploy.Contrib 13.3.0" installed. The v8 site has "Umbraco.Deploy.Contrib 4.4.0" 
I copied "\App_Plugins\DocTypeGridEditor" from the v8 site into the empty v13 site at "UmbracoProject\App_Plugins\DocTypeGridEditor" along with any custom Grid-related folders in the v8 "App_Plugins" folder.

I copied the "grid.editors.config.js" file from v8 ("\Config\" folder) into both "UmbracoProject\Config\" and "UmbracoProject\wwwroot\Config\" (since I wasn't sure where the code would look for it).

I also followed @ronaldbarendse's suggestion to import the schema items first, so when I did the import I only selected the bottom two checkboxes (excluding the Content/Media importing). That completed without any errors. 

But when I then ran it again, including the three options (only excluding Media files, since I used Azure Storage Explorer to copy the media files down separately first), I get this error:

```
EXCEPTION:

Umbraco.Deploy.Core.Exceptions.ImportArtifactsUnhandledException: An unhandled exception has occurred during the import.
   at Umbraco.Deploy.Infrastructure.Work.WorkItems.ImportWorkItem.ExecuteAsync(IWorkContext context, CancellationToken token)

INNER:
  Umbraco.Deploy.Core.Exceptions.ProcessArtifactException: Process pass #5 failed for artifact umb://document/edcd7ae1056b47889bed8ce1a59d0629.
     at Umbraco.Deploy.Infrastructure.ArtifactImportExportService.ImportArtifactsAsync(IArtifactImportProvider artifactImportProvider, ImportArtifactOptions options, IProgress`1 progress, CancellationToken cancellationToken, String[] entityTypes)
     at Umbraco.Deploy.Infrastructure.Work.WorkItems.ImportWorkItem.ExecuteAsync(IWorkContext context, CancellationToken token)

  INNER:
    System.InvalidOperationException: Migrating legacy grid settings failed, because property type with alias 'setting_class' could not be found.
       at Umbraco.Deploy.Infrastructure.Migrators.GridPropertyTypeMigrator.MigrateGridSettings(IDictionary`2 gridConfig, IDictionary`2 gridStyles, IContentType contentType, IContextCache contextCache)
       at Umbraco.Deploy.Infrastructure.Migrators.GridPropertyTypeMigrator.MigrateGridSettings(JToken gridConfig, JToken gridStyles, Guid contentElementTypeKey, BlockGridConfiguration configuration, IContextCache contextCache)
       at Umbraco.Deploy.Infrastructure.Migrators.GridPropertyTypeMigratorBase.Migrate(IPropertyType propertyType, Object value, IDictionary`2 propertyEditorAliases, IContextCache contextCache)
       at Umbraco.Deploy.Core.Migrators.PropertyTypeMigratorCollection.TryMigrate(IPropertyType propertyType, Object value, IDictionary`2 propertyEditorAliases, String contentTypeAlias, IContextCache contextCache, Object& migratedValue)
       at Umbraco.Deploy.Infrastructure.Connectors.ServiceConnectors.ContentConnector.ContentConnectorBase`2.UpdatePropertyType(TContent content, IDictionary`2 artifactProperties, Boolean currentContentIsPublished, IPropertyType propertyType, IEnumerable`1 cultures, IEnumerable`1 culturesToProcess, IDictionary`2 propertyEditorAliases, IContextCache contextCache)
       at Umbraco.Deploy.Infrastructure.Connectors.ServiceConnectors.ContentConnector.ContentConnectorBase`2.MapContentProperties(TContent content, IEnumerable`1 propertyTypes, IDictionary`2 artifactProperties, Boolean currentContentIsPublished, IEnumerable`1 culturesToProcess, IDictionary`2 propertyEditorAliases, IContextCache contextCache)
       at Umbraco.Deploy.Infrastructure.Connectors.ServiceConnectors.ContentConnector.DocumentConnector.MapVersion(IContent content, IContentType contentType, DocumentVersion version, Boolean currentContentIsPublished, IEnumerable`1 culturesToProcess, IDictionary`2 propertyEditorAliases, IContextCache contextCache)
       at Umbraco.Deploy.Infrastructure.Connectors.ServiceConnectors.ContentConnector.DocumentConnector.Process5(DeployState state, IDeployContext context, Int32 pass)
       at Umbraco.Deploy.Infrastructure.Connectors.ServiceConnectors.ContentConnector.DocumentConnector.Process(ArtifactDeployState`2 state, IDeployContext context, Int32 pass)
       at Umbraco.Deploy.Infrastructure.ArtifactImportExportService.ImportArtifactsAsync(IArtifactImportProvider artifactImportProvider, ImportArtifactOptions options, IProgress`1 progress, CancellationToken cancellationToken, String[] entityTypes)

```

This is the first time I'm attempting to use Deploy Export/Import for Migrating, so I'm not what else I'm missing.

**Comment by hfloyd** [comment]
Looking at the resulting crazy collection of doctypes generated from the successful "schema only" import, I decided to leave the legacy grid properties "as-is" for now. I will handle a more manual conversion to a newer version (using Block List and/or Block grid). I wiped the v13 db back to empty, and removed the code for `ReplaceGridDataTypeArtifactMigrator`, `ReplaceDocTypeGridEditorDataTypeArtifactMigrator`, `GridPropertyTypeMigrator`, and `DocTypeGridEditorPropertyTypeMigrator` from the composer.   I was them able to import the schema and content without any errors.

**Comment by ronaldbarendse** [comment]
I've been looking at the errors reported here again and then noticed @hfloyd mentioned removing multiple migrators, which might be the cause of the issue: `ReplaceDocTypeGridEditorDataTypeArtifactMigrator` and `DocTypeGridEditorPropertyTypeMigrator` already inherit from `ReplaceGridDataTypeArtifactMigrator` and `GridPropertyTypeMigrator`, respectively.

If you want to support migrating DocTypeGridEditor, you only need to add the `ReplaceDocTypeGridEditorDataTypeArtifactMigrator` to migrate the data type (configuration) and `DocTypeGridEditorPropertyTypeMigrator` to migrate the content property data. These migrators will revert to the base implementation for non-DocTypeGridEditor grid controls/values.

Adding multiple artifact migrators to migrate the `Umbraco.Grid` editor will only result in using the first registered migrator, as part of the data type migration is changing the editor alias to `Umbraco.BlockGrid`. However, all property type migrators will be used, as that uses the editor alias stored in the artifact (used when exporting the content) and the current one (after the data type is migrated)... So if you're adding both property type migrators, you will most likely get the exception that's posted here.

I'm not 100% sure whether this is the root cause of the issue though, because the stack trace of the `System.InvalidOperationException: Migrating legacy grid failed, because content type with alias 'brancheSlider' could not be found (in the Block Grid configuration).` exception isn't shared... Looking at the source code, this exception can be thrown for either `GridPropertyTypeMigrator` or `DocTypeGridEditorPropertyTypeMigrator` (as you can see in the [Deploy Contrib source code](https://github.com/umbraco/Umbraco.Deploy.Contrib/blob/e7b9f0d0521940948ba35337b2302f3d9068ec8f/src/Umbraco.Deploy.Contrib/Migrators/DocTypeGridEditorPropertyTypeMigrator.cs#L62-L63)).

What I did notice though, is that the `GridPropertyTypeMigrator` expects the element type alias to be prefixed with `gridEditor_` (as that's what `ReplaceGridDataTypeArtifactMigrator` uses as convention), but the exception that's thrown when it can't find it doesn't include this prefix in the error message... So that might explain the confusion about whether the element type exists or not 🤓

I'll make sure to fix this 'typo' in a future Deploy version. To be able to provide further support, please provide the code that configures the migrators and complete error details (including stack traces). You can also do your own debugging by inheriting from `ReplaceDocTypeGridEditorDataTypeArtifactMigrator` and `DocTypeGridEditorPropertyTypeMigrator`, overriding the different methods (see [documentation](https://docs.umbraco.com/umbraco-deploy/13.latest/deployment-workflow/import-export/import-with-migrations#grid-to-block-grid)), add breakpoints and ensuring you only register your own custom migrators!

**Comment by hfloyd** [comment]
Thanks for looking so closely into this, @ronaldbarendse ❤️

The grid is pretty messy in this site, so I think for now I'll just use it as-is, and do whatever needs to be done to get it functional, then have the client start moving content over to a  block list property manually, with some better architecture.
