### ISSUE TITLE
Tree restore for forms doesn't work with Deploy 14

### ISSUE THREAD

**Issue by amirkhan81** [umbraco/Umbraco.Deploy.Issues#241]
### Issue description

Umbraco version: 14.3.1
Forms version: 14.2.0

When making edits in the live environment to a workflow like updating the email address for a send email with template workflow, the updates don't sync back to local with a tree restore.

---
_This item has been added to our backlog AB#45925_

**Comment by ronaldbarendse** [comment]
Hi @amirkhan81, the tree restore of forms (and other custom entities) has been fixed in 14.2.1 and 15.0.1.

Since v14 and the Bellissima backoffice, the concept of trees have changed significantly and some responsibility has moved to the front-end, making the server-side less aware of the UI (specifically where trees are rendered). However, Deploy still requires a 'tree alias' to know what entity type to use for the tree restore action. This resulted in a discrepancy when trying to do a forms tree restore, which we've fixed by falling back to the entity type already known on the front-end. We'll make sure this is aligned in future versions, but that will require changing the registration of custom entities in Deploy, so will likely be a next major...
