### ISSUE TITLE
Umbraco.Deploy.OnPrem nuget packages interfere with logging for all other components

### ISSUE THREAD

**Issue by AnnaTornroth-NLTG** [umbraco/Umbraco.Deploy.Issues#242]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13.3.3

### Bug summary

We get several error messages in the console connected to SignalR.
This is one of all the error messages we get:
<img width="295" alt="Error" src="https://github.com/user-attachments/assets/f06fe6d2-2c4b-4558-8750-9f2433d204ca">

Unfortunately, the logging is very unclear.
When we uninstall that package, everything works without problems.

### Steps to reproduce

Install Umbraco.Deploy.OnPrem nuget package.

**Comment by ronaldbarendse** [comment]
> When we uninstall that package, everything works without problems.

When looking at the URL and stack trace of the error, it looks like custom code is overwriting the Deploy deploy/restore SignalR hub, hence breaking Deploy when installed. The SignalR URLs used by Deploy are provided via the `Umbraco.Sys.ServerVariables` JavaScript object and should contain:
- `Umbraco.Sys.ServerVariables.umbracoUrls.deployHubUrl` = `/umbraco/backoffice/DeployHub`
- `Umbraco.Sys.ServerVariables.umbracoUrls.restoreHubUrl` = `/umbraco/backoffice/RestoreHub`

These can be inspected via the browser console (when Deploy is installed). One key difference in the URL of the error is the absence of the `/umbraco/backoffice/` part, which will result in using (or trying to use) member authentication for protected endpoints/hubs (like Deploy uses), instead of backoffice user authentication...

Since this doesn't seem like a problem within Deploy itself, I'll close the issue. Feel free to follow up with more information or questions though, as we definitely want to help finding a solution for your issue!

**Comment by AnnaTornroth-NLTG** [comment]
We have tried turning off all other plugins as well as the code we have to overwrite and it doesn't work anyway. 
Can you take a further look at this?

**Comment by AnnaTornroth-NLTG** [comment]
Hi,
We have tried turning off all other plugins as well as the code we have to overwrite and it doesn't work anyway.
Can you take a further look at this?

**Comment by ronaldbarendse** [comment]
> Hi, We have tried turning off all other plugins as well as the code we have to overwrite and it doesn't work anyway. Can you take a further look at this?

I'd recommend first upgrading to the latest CMS and Deploy versions (the reported CMS 13.3.3 version was released 6 months ago and contains multiple moderate security vulnerabilities, see [Security Advisory, October 22, 2024](https://umbraco.com/blog/security-advisory-october-22-2024-patches-for-umbraco-cms-are-now-available/)). I can't replicate the issue on a fresh install and haven't received any feedback on the `Umbraco.Sys.ServerVariables.umbracoUrls` URLs, so don't have anything further to look at...

If updating to the latest versions and removing any other (potentially interfering) plugins doesn't resolve the issue, I'd suggest looking into the hosting environment (which is outside of the support scope of the Deploy issue tracker).
