### ISSUE TITLE
Image isn't transferred in block list settings

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Deploy.Issues#86]
On a Umbraco Cloud project on v9.0.1 and Deploy v9.0.1 and I have a CTA block in block list editor. Futhermore I have other block list editor like a simle Image block.

Both Image and CTA block use Media Picker v3, but Image block has a image property on the element type as Content, while the CTA block has a background image property element type as Settings.

**Local environment**

![image](https://user-images.githubusercontent.com/2919859/140526696-8f0841a2-6fdf-4759-be05-07ed6eaeee49.png)

**Live environment**

![image](https://user-images.githubusercontent.com/2919859/140526817-155807c0-f90b-4e6c-a039-7c9270efe29d.png)

Everything is transferred fine except the missing value in the background image property. I haven't noticed issues with other blocks using Media Picker v3 in Content.

I tried on live environment selecting a specific image, which show this on frontend, but it I do another transfer from local, the image on live isn't updated, but has the previous selected image.

Furthermore I tried transfer media first and confirmed the image exists on live environment and afterwards another transfer, but with same result.

**Comment by AndyButland** [comment]
This looks to be due to a difference in how the CMS serialized the property data for block list items for the "content" and "settings" model values.  More details in the linked PR.

**Comment by ronaldbarendse** [comment]
I've investigated this issue and it's more of an issue in the CMS. I've created an element type with a Textstring, Image Media Picker and Multi URL Picker, used that as both content and settings model in a Block List and got the following JSON stored in the `umbracoPropertyData` table:

```json
{"layout":{"Umbraco.BlockList":[{"contentUdi":"umb://element/d75621a04da74c76af0c90d93ac334fd","settingsUdi":"umb://element/a35b2c8b1e4047cf91863fb586319470"}]},"contentData":[{"contentTypeKey":"cf14b515-1d70-4a9f-979f-750124248742","udi":"umb://element/d75621a04da74c76af0c90d93ac334fd","text":"Content","image":"[\r\n  {\r\n    \"key\": \"899aebbe-19c2-4cac-8848-d43bfbce3847\",\r\n    \"mediaKey\": \"db105916-3254-461d-8920-f9fde51ccd38\",\r\n    \"crops\": [],\r\n    \"focalPoint\": {\r\n      \"left\": 0.5,\r\n      \"top\": 0.5\r\n    }\r\n  }\r\n]","buttons":"[{\"name\":\"Home\",\"udi\":\"umb://document/989ce4288bbf42c88df26f07f992857d\"},{\"name\":\"Home\",\"target\":\"_blank\",\"udi\":\"umb://document/989ce4288bbf42c88df26f07f992857d\"}]"}],"settingsData":[{"contentTypeKey":"cf14b515-1d70-4a9f-979f-750124248742","udi":"umb://element/a35b2c8b1e4047cf91863fb586319470","text":"Settings","image":[{"key":"90dfc419-325e-4bab-8b7a-148e8318f471","mediaKey":"7e6d3e37-0003-4256-99ef-d3f1f0ca4954","crops":[],"focalPoint":{"left":0.5,"top":0.5}}],"buttons":[{"name":"Home","target":"_blank","udi":"umb://document/989ce4288bbf42c88df26f07f992857d","url":"/","icon":"icon-document","published":true,"trashed":false},{"name":"Home","udi":"umb://document/989ce4288bbf42c88df26f07f992857d","url":"/","icon":"icon-document","published":true,"trashed":false}]}]}
```

Notice that the actual value doesn't contain any whitespace, but:
- Both the content `image` and `buttons` are JSON data stored as string values
- The content `image` JSON data contains whitespace (encoded as `\r\n` and spaces), but `buttons` doesn't
- The settings `image` and `buttons` are actual JSON values, but are not transformed from the back-office editor to database values (which is only visible for `buttons`, as the `IDataValueEditor.FromEditor()` implementation of [`MultiUrlPickerValueEditor`](https://github.com/umbraco/Umbraco-CMS/blob/5bfab13dc5a268714aad2426a2b68ab5561a6407/src/Umbraco.Infrastructure/PropertyEditors/MultiUrlPickerValueEditor.cs#L147) actually transforms the data, but the [`BlockEditorPropertyEditor`](https://github.com/umbraco/Umbraco-CMS/blob/23d21062773889916fbe2c14f32158dce282e1f1/src/Umbraco.Infrastructure/PropertyEditors/BlockEditorPropertyEditor.cs#L187) doesn't for settings data)

After restoring this node data using Deploy, the value stored in the `umbracoPropertyData` contains whitespace (indented JSON) and only the content `image` and `buttons` is transferred (which explains why the image isn't transferred, so that confirms this issue):

```json
{
  "layout": {
    "Umbraco.BlockList": [
      {
        "contentUdi": "umb://element/d75621a04da74c76af0c90d93ac334fd",
        "settingsUdi": "umb://element/a35b2c8b1e4047cf91863fb586319470"
      }
    ]
  },
  "contentData": [
    {
      "contentTypeKey": "cf14b515-1d70-4a9f-979f-750124248742",
      "udi": "umb://element/d75621a04da74c76af0c90d93ac334fd",
      "text": "Content",
      "image": "[\r\n  {\r\n    \"key\": \"899aebbe-19c2-4cac-8848-d43bfbce3847\",\r\n    \"mediaKey\": \"db105916-3254-461d-8920-f9fde51ccd38\",\r\n    \"crops\": [],\r\n    \"focalPoint\": {\r\n      \"left\": 0.5,\r\n      \"top\": 0.5\r\n    }\r\n  }\r\n]",
      "buttons": "[{\"name\":\"Home\",\"udi\":\"umb://document/989ce4288bbf42c88df26f07f992857d\"},{\"name\":\"Home\",\"target\":\"_blank\",\"udi\":\"umb://document/989ce4288bbf42c88df26f07f992857d\"}]"
    }
  ],
  "settingsData": [
    {
      "contentTypeKey": "cf14b515-1d70-4a9f-979f-750124248742",
      "udi": "umb://element/a35b2c8b1e4047cf91863fb586319470",
      "text": "Settings",
      "image": null,
      "buttons": null
    }
  ]
}
```

I think we can start by making sure Deploy transfers the data without (unnecessarily) transforming the data and ensuring both the actual JSON and serialized string versions are supported. When that's done, we can streamline the data the CMS stores:
- Store actual JSON data (not the string versions containing whitespace)
- Ensure the settings data is correctly transformed

**Comment by hfloyd** [comment]
I just came across the same issue, with a MediaPicker on a "Settings" type not getting it's data transferred.
Umbraco Id
Umbraco 8.17.1
Deploy 4.4.0.0
Forms 8.9.1

**Comment by AndyButland** [comment]
This looks to have been resolved now with [a fix to CMS](https://github.com/umbraco/Umbraco-CMS/pull/11722), unifying how "content" and "settings" items are stored on block list editors.

I've retested this with the CMS fix applied and see that the media picker details are transferred for block list items now whether stored under "Content" or "Settings, so we don't need the changes prepared for Deploy.
