### ISSUE TITLE
img alt tags not transferring up the queue

### ISSUE THREAD

**Issue by jbrobinson** [umbraco/Umbraco.Deploy.Issues#87]
Umbraco Cloud Umbraco 8.17.1 | Deploy 4.2.0.0 | Forms 8.8.0

On a page (this seems to happen on any page with an RTE where an image is added.)

•	Insert image to RTE within the copy.
•	Add alt tag copy in media picker
•	Edit source in RTE to add class=”left” to the img tag for instance. 
•	Save and publish.
•	Refresh the browser (Chrome or Firefox)
•	Use inspector or view source to see if image tag contains proper alt attribute.
•	Go back to backoffice in Dev
•	Add page to transfer queue
•	Push transfer queue to staging
•	Use browser to check page in staging
•	Check view source or inspector 
•	Alt tag typically is missing but the text of the alt that was written in the alt tag of the media picker is there.

For example:
`<img class="left" src="/media/2mbhjl4j/rowland-family.jpg" alt="SFU TEST">` is the source code in the RTE on Dev

Once transferred up the queue to staging and checked in the browser source code it returns with the following
`<img class="left" src="/media/2mbhjl4j/rowland-family.jpg" sfu test">`

This same scenario does not seem to occur if the source of the RTE is not opened. 
Umbraco Support has been able to recreate the exact scenario outlined above.
 
As stated previously, this happens on any page where an image is inserted into an RTE. It is almost as if the switch from source to WYSIWYG in the RTE is writing code incorrectly but isn’t showing up until the file is transferred. Could be an issue with the database transferring from one environment to the other?

**Comment by AndyButland** [comment]
Certainly sounds odd, but I've tried replicating this with the latest code - 4.4.0-rc002 for Deploy - and I'm not seeing the same behaviour,  The alt text and CSS class are rendered correctly on both environments.

**Comment by jbrobinson** [comment]
@AndyButland, thank you for your response. We are on the cloud 
Umbraco 8.17.1 | Deploy 4.2.0.0 | Forms 8.8.0
Which could be the issue. I know that Support has been able to recreate this same outcome on this project following the steps outlined above. I was asked to report the Issue here. I realize now that I should have included the version and deploy information. Many apologies.

**Comment by jbrobinson** [comment]
I have updated the Deploy to 4.4.0 and this issue is still occurring.
 
![image](https://user-images.githubusercontent.com/1063129/142509881-73610ad3-69b5-41e2-b472-c5891902a52f.png)

**Comment by AndyButland** [comment]
I'm afraid I'm still unable to replicate the problem.  Given you have a ticket open with support please can I ask you go back to them and ask them to re-confirm they can replicate the issue and then escalate to me internally?  Perhaps if I have access to your specific project or an example with the scenario already prepared I'll be able to see what differs with the tests I'm doing.  Thanks.

**Comment by jbrobinson** [comment]
Andy, thank you for your response. I have returned it to support. Simon
Fugl was able to recreate this result on Nov. 8. I have returned it to
support after upgrading to Deploy 4.4.0. Muslim is checking with Simon to
see how he recreated the issue on our project. I'm assuming he used the
same steps I have outlined previously. Any help would be greatly
appreciated. My team and supervisors have concerns about our accessibility
compliance becoming a major issue. Missing alt tags is definitely a problem.

**Comment by AndyButland** [comment]
@jbrobinson - just to update, with Simon's help I've been able to replicate it now and have a fix in for review.  All being well we'll get this resolved for the next release.

**Comment by jbrobinson** [comment]
Andy, that is great news. I would love to hear the full analysis on the issue.

**Comment by AndyButland** [comment]
Happy to share, though it's a little involved and partly involves some history and legacy handling... in summary though there's some logic built into Deploy when transforming rich text values to parse things like links and media files, to make sure all the dependencies are picked up and transferred as well.  That uses regular expressions to parse out the `src` parameter and do some manipulations on the way out and way in... and it wasn't correctly handling an empty `src` attribute.

Umbraco will strip out the src and replace it with another attribute indicating the ID of the media item when saving the value from a rich text editor, but even after doing that, the src field isn't usually empty.  If you add a new image via the media picker into a rich text editor, you'll see there's  a `?width=X&height=Y` querystring.  Hence we don't normally see the problem.

Your images though, which I can see are on older articles and so were perhaps added using an earlier version, don't have these querystrings and hence hit the bug.  The issue manifests itself in that it incorrectly replaces part of the `alt` attribute too, so that's why you see empty or odd values in the mark-up.

**Comment by jbrobinson** [comment]
Aha! That makes sense. Your assessment is correct about many of the images having been added in an earlier version. We started using Umbraco earlier this year right before the release of Media Picker 3

**Comment by jbrobinson** [comment]
@AndyButland  I don't know if the next release has happened for our project yet, but this issue is still ongoing as described above. I would not call it closed yet. 

I think I found a stale issue #30 that may be related to this issue. It definitely seems to show many of the same symptoms I reported previously. I do have the Max size for inserted images set to 0. When set to any value besides 0 the alt tag appears as expected when transferred up the queue. I set this to 0 initially because our team controls height and width through CSS. 

If this is something that we just need to deal with to make this work, so be it, but I don't understand why this is an option of the RTE datatype if it will just break other attributes in the img tag. Especially when it comes to the alt attribute, which is paramount to accessibility and important to SEO.

Thank you,
Jay

**Comment by AndyButland** [comment]
Hi Jay - we tend to close issues once the code to resolve them has been reviewed, merged and a release has been identified, rather than when the release has actually gone out.  The release labels show when you can expect it - in 4.4.1 and 9.2.0 - which I'm hoping we'll get out next week.

And yes, that related issue is the same thing.  As we discussed above, the issue doesn't occur if the image has a querystring used for resizing, it's only when this is missing that the issue manifests itself.  So be using this setting as "0" there will be no querystring, and then we have the problem.

So as a work around, you can use this setting, ensuring a querystring and avoiding the problem.

But as of the next release, the issue should be fixed whether you want to do this or not.
